### PR TITLE
Update dynamic_clamp.ino

### PR DESCRIPTION
**Pull request by christianrickert**
I think it would make sense to scale the intercept of the "injectionCurrent",
in addition to the scaling of "outputSlope", before sending it to the amplifier
for interpretation:

L53:    const float outputIntercept = 2386/gain_OUTPUT

This effectively (sic!) results in a rescaling of both the outputSlope and the outputIntercept
for injectionCurrent calculation:

L168:  injectionCurrent = (outputSlope * injectionCurrent + outputIntercept)/gain_OUTPUT;

To keep the code consistent, I have only made the change to L53.

### CODE REVIEW

**Comment by nsdesai** [comment]
I'm not sure I understand this edit, and I suspect it's because I used injectionCurrent inconsistently in L168.

On the left-hand side, injectionCurrent is in ADC units. On the right-hand side, injectionCurrent is in pA.. This means that outputSlope is in ADC/pA, whereas outputIntercept is in ADC.

If you were to divide outputIntercept by gain_OUTPUT in L53, you'd just need to multiply it by the same in L168 to get the right units.

Unless I'm missing something?

**Comment by christianrickert** [comment]
I think the problem is introduced at the level of the output calibration:
We are, in fact, calibrating the digital commands of the Teensy [DAC] against the voltage output of the Teensy and its attached electronic circuits [V]. Because the amplifier interprets any voltage commands as current, given its _gain_INPUT_ in [A/V], both the voltage command from the calculated current injection [DAC] as well as the voltage offset from the intercept [DAC] will first be converted to a voltage [V] by the digital-to-analog unit and second to a current [A] by the amplifier.

By dividing _outputSlope_ with _gain_INPUT_, we can effectively treat _injectionCurrent_ in the first term of the summation as a current. However, since the _outputIntercept_ corrects for a voltage offset, it's logical to scale it by _gain_INPUT_, too.

Not scaling _outputIntercept_ in the current calculation equation will result in a bigger current offset at the amplifier level, which could of course also be corrected for with the amplifier controls.

**Comment by nsdesai** [comment]
Hey Christian,

I'm still confused. Maybe if you rewrote both L53 and L168 in the way you think they should be? Just dividing L53 by gain_OUTPUT alone doesn't work unless you were to change the numerator as well. For example, with a gain_OUTPUT of 400 pA/A, the line L53 would have to be:

outputIntercept = 954400 / gain_OUTPUT

The only way we could keep it as L53 = 2386/gain_OUTPUT would be to change L168 as well. In particular, to change it to: 

injectionCurrent = outputSlope * injectionCurrent + ouputIntercept * gain_OUTPUT

(Again, confusingly,  injectionCurrent represents DAC on the left and pA on the right.)

My way of thinking is that outputIntercept should be the DAC number that results in a voltage command of 0 V being sent to the amplifier (regardless of its gain). That is, outputIntercept is *independent* of the amplifier gain. And so, why rewrite things to introduce a dependence on amplifier gain?

Niraj

**Comment by christianrickert** [comment]
Hey Niraj,

> I'm still confused.

And that is definitely my fault. - My sincerest apologies.

There is two points that contributed to my confusion (and my proposed code alteration being wrong):

The first point is that the _outputIntercept_ is correcting for an offset of the Teensy/circuits *before* being interpreted by the amplifier (as in: disconnected from). If the voltage output is zero after the calbration, the _gain_OUTPUT_ by the amplifier doesn't matter anyway.
However, a hypothetical offset of 500 DAC units from the Teensy (with whatever resulting voltage command equivalent) will produce a different current offset at an Axonpatch 200B (2000 pA/V) versus an Axonpatch 700B (400 pA/V). This difference in voltage command interpretation is a given and has to be corrected for at the amplifier level - with the current offset dial.

Now comes the second point: Wouldn't the same logic apply to both the _outputIntercept_ and the _inputIntercept_?

With the line of argumentation we have established, shouldn't the  _inputIntercept_ then, too, be independent from the amplifier input gain (50 mV/mV) - i.e. not be divided by _gain_INPUT_ (L:51)?

Chris

**Comment by nsdesai** [comment]
Hi Christian, 

Let’s leave aside the question of a hypothetical offset for the moment. (I'll come back to it at the end.)  inputIntercept and outputIntercept are not quite the same. The equation of a line is Y = m*X + b. In the input case, ADC is the X-coordinate. But in the output case, DAC is the Y-coordinate.

INPUT
If you look at Figure 2B of the paper, the relationship between the amplifier output voltage V_IN and the Teensy input voltage V_OUT is:

V_OUT = A*V_IN + B

where A and B are constants that depend on the resistor choices and the positive power supply (V+). 

Now, ADC = 4096*V_OUT/3.3 and V_IN = g*V_m, where g is the amplifier gain and V_m is the membrane potential. Substituting for V_OUT and V_IN and inverting the equation, we get the following for the relationship between ADC and V_m:

Vm = (1/g)*(3.3/4096)*(1/A) * ADC – (1/g)*(B/A)

***Notice that both the slope and the intercept depend on the amplifier gain g (or more precisely, they depend on 1/g).***

OUTPUT
Say that amplifier converts the dynamic clamp command voltage V_DC into current I using a gain k (equal, for example, to 400 pA/V). Then we have:

I = k * V_DC

If you look at Figure 2D, we can substitute for V_DC in terms of the Teensy output voltage V_DAC:

I = k*C*V_DAC + k*D

where C and D are constants that depend on the resistor choices and the negative power supply (V-). Now, V_DAC is related to DAC by V_DAC = 3.3 * DAC / 4096. Substituting this in the above equation and inverting it, we have:

DAC = (1/k)*(1/C)*(4096/3.3) * I – (D/C)*(4096/3.3)

***Notice that the slope depends on the amplifier gain k but the intercept is independent of k.***

OFFSET
You raised the issue of a hypothetical offset in the Teensy DAC. For example, let’s say that the relationship between V_DAC and DAC is actually V_DAC = 3.3*(DAC+E)/4096, where E is some fixed error. If we use this and redo the algebra, we instead get the following for how DAC depends on I:

DAC = (1/k)*(1/C)*(4096/3.3) * I – (D/C)*(4096/3.3) – E

***The outputIntercept is now different than it was before (by an additive factor -E), but it’s still independent of the amplifier gain k.***

Another way to think about it is that, when we specify zero current (I=0), outputIntercept should be equal to whatever DAC value makes the output of the dynamic clamp circuit V_DC equal to zero -- regardless of the gain of the amplifier.

Let me know what you think – and especially if I messed up the algebra, which is possible :)

Niraj

**Comment by christianrickert** [comment]
(I checked your algebra with pen and paper and the equations are correct.)

Until now, I hadn't considered the **effects of the breadboard electronics**,
and how they propagate a pre-amplified signal to the Teensy input /
how the additive factor E translates into the final Teensy output.

Thank you very much for your detailed explanation!
I definitely owe you a beer!   🍺 🍺

**Pull request closed without merging**
